print("how old are you?", end=' ')
age = input()
print("how tall are you?", end=' ')
height = input()
print("how much do you weigh?", end=' ')
weight = input()
print(f"so your age is {age} old,{height} tall and {weight} heavy")
